inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-capybara

AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  AllowedParentClasses: [ApplicationService]

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Rails/RakeEnvironment:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Style/Documentation:
  Enabled: false
