inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-capybara

AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  AllowedParentClasses: [ApplicationService]

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Max: 10
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpecRails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Enabled: false
